---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: Creates directory
  file:
    path: /home/ubuntu/dist
    state: directory
      
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Extract apt packages
  become: true
  copy:
    src: /root/project/backend/dist.tar.gz
    dest: /home/ubuntu

- name: Extract backend and start node server
  shell: |
    cd /home/ubuntu
    tar -xf dist.tar.gz
    rm -rf dist.tar.gz
    cd dist
    npm i
    pm2 start main.js --update-env


    

