---
- name: Extract apt packages
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
    
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start job
  become: true
  shell: |
    cd /home/ubuntu/
    tar xzvf artifact.tar.gz
    pwd
    cd backend
    pm2 stop default
    pm2 start npm -- start

