---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: Extract apt packages
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz
    
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "install npm packages"
  become: true
  command: npm install
  args:
    chdir: /home/ubuntu/backend    

- name: "compile npm packages"
  become: true
  command: npm run build
  args:
    chdir: /root/backend

- name: Start server
  become: true
  command: pm2 start npm -- run start
  
  args:
    chdir: /root/backend/dist  
    

